from datetime import datetime
from typing import Protocol
from uuid import UUID


class IAccountStateManager(Protocol):
    async def acquire(self, account_id: UUID) -> None: ...
    async def release(self, account_id: UUID) -> None: ...
    async def get_connections(self, account_id: UUID) -> int: ...
    async def mark_rate_limited(self, account_id: UUID, retry_after: int) -> None: ...
    async def restore_rate_limit(self, account_id: UUID, until: datetime) -> None: ...
    async def is_rate_limited(self, account_id: UUID) -> bool: ...
    async def clear_rate_limit(self, account_id: UUID) -> None: ...
    async def get_all_connections(self) -> dict[UUID, int]: ...
