from typing import Protocol
from uuid import UUID

from src.domain.models.user import User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_by_username(self, username: str) -> User | None: ...

    async def get_by_api_key_prefix(self, prefix: str) -> User | None: ...

    async def list_all(self) -> list[User]: ...

    async def create(self, user: User) -> User: ...

    async def update(self, user: User) -> User: ...

    async def count(self) -> int: ...
